FROM ruby:2.7-alpine

LABEL maintainer="Kunal Nagar <knlnagar@gmail.com>"

RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/ nodejs
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/ npm
