FROM ruby:2.6-alpine

LABEL maintainer="Kunal Nagar <knlnagar@gmail.com>"

RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/ nodejs=12.18.2-r2
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/ npm=12.18.2-r2
