FROM ruby:2.6-alpine

LABEL maintainer="Kunal Nagar <knlnagar@gmail.com>"

RUN apk add  --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/ nodejs=12.18.0-r2
RUN apk add --update nodejs-npm
